### ISSUE TITLE
Disable PCH for Game/GameSys/TypeInfo.cpp

### ISSUE THREAD

**Issue by ghost** [ljbade/doom3.gpl#2]
PCH needs to be disabled for Game/GameSys/TypeInfo.cpp because it uses an ugly hack to basically modify the header files it #includes.
Specifically, it does this:
# define private public
# define projected public

And then it includes all the header files it needs, including the precompiled header. If PCH is left enabled, the hack has no effect on the precompiled header (because it's already been precompiled), so TypeInfo.cpp fails to compile with a bunch of errors about accessing private variables.

**Comment by ljbade** [comment]
Thanks for the info.

I haven't touched the code in a while so if you have a working patch please send it to me and I'll add it.

**Comment by ghost** [comment]
Two fixes at https://github.com/ljbade/doom3.gpl/pull/4
